---
- name: Pre setup kubernetes
  hosts: all
  tasks:
    - name: Add sysctl value
      copy: 
        src: file/99-kubernetes.conf
        dest: /etc/sysctl.d/99-kubernetes.conf

    - name: Load sysctl value
      shell: >
        sysctl --system

    - name: Install docker
      shell: >
        curl https://releases.rancher.com/install-docker/20.10.sh | bash -

    - name: Enable and start service docker
      shell: >
        systemctl enable --now docker

    - name: Add rke user to docker group
      shell: >
        usermod -aG docker rke

    - name: be sure firewalld is disabled
      systemd: name=firewalld enabled=no

    - name: be sure firewalld is stopped
      systemd: name=firewalld state=stopped
      ignore_errors: yes
