---
- name: setup bastion kubernetes
  hosts: bastion
  tasks:
    - name: Download kubectl
      shell: > 
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl

    - name: Set kubectl executeable
      become: true
      shell: >
        chmod +x ./kubectl

    - name: Move kubectl
      become: true
      shell: >
        mv ./kubectl /usr/local/bin/kubectl

    - name: Download rke binary
      shell: >
        curl -s https://api.github.com/repos/rancher/rke/releases/latest | grep download_url | grep amd64 | cut -d '"' -f 4 | wget -qi -

    - name: Set rke executeable
      become: true
      shell: >
        chmod +x rke_linux-amd64

    - name: Move rke
      become: true
      shell: >
        mv rke_linux-amd64 /usr/local/bin/rke

    - name: Get Helm Installer
      shell: >
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3

    - name: Set kubectl helm installer
      shell: >
        chmod 700 get_helm.sh

    - name: Install Helm
      shell: >
        ./get_helm.sh
